language: ruby
addons:
  apt:
    packages:
      - coreutils
rvm:
- 2.0.0
- 1.8
- 1.9.3
- jruby-19mode
- rbx-2
env:
- MODE=check
- MODE=run
script:
#- timeout --help
- printenv
- script -c make out.${MODE}
- ./report.rb out.${MODE}
