language: ruby
addons:
  apt:
    packages:
    - coreutils
rvm:
- 2.4.0
- 2.0.0
- 1.8
- 1.9.3
- jruby-19mode
- rbx-3
env:
  global:
  - NO_EXCLUDE=yes
  matrix:
  - MODE=check
  - MODE=run
script:
- printenv
- script -c make out.${MODE}
- ./report.rb out.${MODE}
after_script:
- scripts/submit.sh
branches:
  only:
    - master
